### ISSUE TITLE
/search endpoint massive performance issues

### ISSUE THREAD

**Issue by ploiu** [ploiu/file_server#47]
since search is empty, it pulls every file first to check their tags. The search function should either be smarter or have a faster implementation if it's going to be stupid.

apparently also just happens when you have a lot of files

# File\_Server search

## What we need

a quick way to retrieve all files that partially match the supplied title, and fully match the supplied tags

## Current Steps To Achieve that but Slowly (8N steps, where N = Number of Files)

1.  retrieve all files that partially match `title`, even if `title` is empty
2.  for all matched files:
    1.  get all tags for file
    2.  if file has a parent folder:
        1.  get all parent folders for the file's immediate parent
        2.  get the file's immediate parent
        3.  retrieve all tag titles for all of the file's parents
    3.  retrieve all tag titles for the file
    4.  create an intersection of the tags requested vs the tags on the file + parent folders
    5.  include only those files where the length of #4 matches the length of `tags`

## Potential Faster Steps

1.  if `title` is empty (4N, where N = Number of Folders):
    - [ ]   database query to query `File_Tags` for all files that have all passed `tags`
    - [ ]   database query to query `Folder_Tags` for all folders that have any passed `tags`
        
        *   Example Result for `tags` \[tag1, tag2, tag3\]
        
        _content\_copy_
        
        ```jsonc
        // you can see that some folders are part of the same "chain" of folders
        // and others are completely estranged from the rest  
          [
            {
              "id": 1,
              "name": "top",
              "parentId": null,
              "tags": [
                "tag1"
              ]
            },
            {
              "id": 6,
              "name": "middle",
              "parentId": 1,
              "tags": [
                "tag2",
                "tag3"
              ]
            },
            {
              "id": 3,
              "name": "top2",
              "parentId": null,
              "tags": [
                "tag2"
              ]
            },
            {
              "id": 4,
              "name": "bottom",
              "parentId": 6,
              "tags": [
                "tag1"
              ]
            },
            {
              "id": 10,
              "name": "someotherfolder",
              "parentId": 7,
              "tags": [
                "tag3"
              ]
            }
          ]
        ```
        
        - [ ]  ideally we want to have a **copy** of this list, but _reduced_ to have the first folder with all the tags:
        
        _content\_copy_
        
        ```json
          [
            {
              "id": 6,
              "name": "middle",
              "parentId": 1,
              "tags": [
                "tag2",
                "tag3"
              ]
            }
          ]
        ```
        
        *   this list will contain folders that have all the tags, meaning all subfolders and child files will have the right tags
    3. [ ] for each folder in the deduplicated list (2N if combine \#3 and \#4):
        1. [ ]  retrieve all child folders recursive (1 query)
        2. [ ]  retrieve all child files (1 query)
        3. [ ] retrieve all child files of those child folders (1 query, and can condense #2 and #3 if need be)
        4. [ ] add those child files into the list of files
    4. [ ] for each folder not in the deduplicated list (2N):
        1. [ ] retrieve all immediate child files with the rest of the tags (1 query)
        2. [ ] retrieve all child folders recursive (1 query)
        3. [ ] for each child folder, retrieve all child files with the rest of the tags (1 query / folder, or 1 query if we combine \#2 and \#3 from step \#3 above)
2. [ ]  if `title` is not empty (4N + 1, where N = Number of Folders):
    1. [ ] repeate all steps in \#1
    2. [ ] limit files by any that match `title` by regex
